### ISSUE TITLE
TLS config problem

### ISSUE THREAD

**Issue by hex-m** [performous/web#4]
Firefox 47 won't let me access performous.org as the certificate is only valid for "    *.github.com github.com *.github.io" and HSTS is activated.

**Comment by Baklap4** [comment]
Guys what are we gonna do about this?
If needs to be i can host it at my server with valid certificates using letsencrypt. Or the certificatea already purchased.

Other solution is to host this at GitHub Pages.

**Comment by yepyepyep4711** [comment]
my browser made me believe the site was offline. I came here to offer the same help as the previous poster (but now I'm just posting this to get notified of updates on this issue ;) )

**Comment by Baklap4** [comment]
since this problem still persists I thought why not host it myself.
The site is available (with ssl) at: https://performous.asgardsings.nl

As said i can easily do the hosting but not without the current server being live @ performous.org

**Comment by nieknooijens** [comment]
I have 3 browsers and they all load the site correctly (firefox on ubuntu, chrome on ubuntu and adblock browser on android). when I switch to https I get an certificate error, making an exception just loads the page. removing the s from https just loads the non-ssl version as normal.

**Comment by LunarLanding** [comment]
Chrome on windows does not load, even if it try to access via http, which is already a tech-savy move that most of your target audience won't try. Plus your site is being penalized on search engines. @Baklap4  's site loads just fine.

**Comment by Baklap4** [comment]
I'd like to get back to this question once every half year, however there's still no progress with this. People are complaining they can't reach the site due to ssl failure.
I've set up 3 different OS'es within virtualboxes, and couldn't reach the normal http version of the website. Quite bothering this..

We have three options: 

1. The one who owns the domain (Vincent) will point in the dns the website to my server (https://performous.asgardsings.nl) 
2. Move away from the github pages certificate and buy/install the required certificate
3. Move away from ssl and just go through http instead.

I'm more fond of the first one. I can easily create a script which has to pull everytime there's been a push to master, and get the new content. That's no biggy.

**Comment by nieknooijens** [comment]
there's also letsencrypt so we don't even need to buy an ssl cert.

**Comment by Baklap4** [comment]
@nieknooijens currently using it at my server, therefore it'll always have a valid certificate.
I bet the website is hosted in a webhost environment instead of a vps, which make the use of letsencrypt barely possible, since many don't support it yet.

**Comment by basisbit** [comment]
This issue is still persistent. As said already on irc, I'd suggest using cloudflare to do the TLS, and continue using github.io for the hosting. Once this solution is set up, it will work fine for years without any additional work. Also, this doesn't introduce any additional dependency which some private hosting or sponsored hosting would add.
Lots of github.io hosted projects do this already (for example the UltraStar Deluxe project) and this is also the suggested solution form github support.

**Comment by Baklap4** [comment]
@basisbit i'm alright with this. However we still need an admin to "fix" this... @yoda-jm @tapio @tronic

**Comment by Baklap4** [comment]
@nieknooijens can you fix this? since you're an admin now aswell?

**Comment by nieknooijens** [comment]
@Baklap4  I'm admin on the github, not on the site.

**Comment by Baklap4** [comment]
Already in 2018.. still no fix.. seriously this can be fixed quite easily, but the domain admin needs to do it...

**Comment by yoda-jm** [comment]
Solution using cloudflare in place (redirecting to github pages).
Tested and running (might still take a few hours for the DNS change to be propagated everywhere).

**Comment by basisbit** [comment]
@yoda-jm in the cloudflare dashboard in the DNS section, please click on the grey cloud next to the www entry. Then the cloud should change into an orange cloud, which once DNS changes propagated, should also fix the TLS issue for the www. tld.

**Comment by yoda-jm** [comment]
It is already in the orange state you mentioned, maybe just some kind of propagation or a weird www -> performous.org redirection that got cached in a wrong way.
