### ISSUE TITLE
Remove master branch or rename gh-pages branch

### ISSUE THREAD

**Issue by Baklap4** [performous/web#9]
### Do you want to request a *feature* or report a *bug*?

Cleanup

### What did you expect to see?

I expected the `master` branch to be the one which is the source of https://performous.org
This wasn't the case. The `gh-pages` branch is the source of our website.

### Cleanup options
1. Remove / archive the `master` branch and rename `gh-pages` branch to `master`
2. Merge `gh-pages` branch into master and delete `gh-pages` branch

**Comment by Baklap4** [comment]
If we want to still use `webconv` we probably just have to create a CI by github actions or with semaphore to publish it to the gh-pages branch.

If we just want to have a static website which it currently is, i'm alright with just deleting the master branch and use find + replace

**Comment by Tronic** [comment]
Maintaining the navigation menu by hand is cumbersome if editing static HTML because the menu needs to be correctly duplicated on each file. So I think the options are either one of:

- Check git log of the last few years for any changes done to HTML files, and backport them to TXT, then re-run webconv and keep using it.
- Install some modern CMS (maybe one that generates static HTML but provides editing in browser) and remake the whole site using themes and everything from the CMS.

Editing those static HTML files combines the worst of both worlds, and thus should be avoided at all cost.

Earlier discussion at https://github.com/performous/web/pull/7#issuecomment-612459579

See for reference:
https://github.com/performous/web/blob/master/htdocs-source/blog.txt
https://github.com/performous/web/tree/master/webconv

You may be able to use the deploy scripts, possibly with modifications, to generate and upload.

**Comment by Tronic** [comment]
The gh-pages branch by Yoda 5 years ago seems to be just a snapshot of the generated site. Possibly with some edits that hopefully can be found by diff on the HTML files itself.

**Comment by yoda-jm** [comment]
Hello,

The branch is used as the default site (hosted on github) : https://github.com/performous/web/settings/pages
This is the official website (performous.org) AFAIR

**Comment by Baklap4** [comment]
Closing this in favor of #13
